# Site settings
title: "Jacob Tomlinson"
email: "jacob@jacobtomlinson.co.uk"
description: "A technology blog by Jacob Tomlinson."
baseurl: ""
url: "http://www.jacobtomlinson.co.uk"
author_name: "Jacob Tomlinson"
title_image: "http://2.gravatar.com/avatar/b7c2d49748426791dc98b8214dfac9d1?s=500"
title_description: "SysOps Engineer who does a bit of DevOps too. Writes code, builds servers and automates things. Currently obsessed with Docker! When he is not tapping away at his keyboard you can usually find him making music, gaming or spending time with his wonderful fianc&#233;e."
google_analytics: "UA-20365477-2"
disqus_account: "jacobtomlinson"
github_repository: "https://github.com/jacobtomlinson/jacobtomlinson.github.io"
addthis_id: "ra-513c6fa83da6ec67"
post_limit: 5

# Social usernames/URLs
twitter_username: "_jacobtomlinson"
github_username:  "jacobtomlinson"
linkedin_link: "http://www.linkedin.com/pub/jacob-tomlinson/34/b67/84"
google_plus_link: "https://plus.google.com/+JacobTomlinson0/"
stackoverflow_link: "http://stackoverflow.com/users/1003288/jacob-tomlinson"

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> using <a href=\"http://jekyllrb.com/\">Jekyll</a>"
footer_right: "<i class=\"fa fa-code\"></i> on <a href=\"https://github.com/jacobtomlinson/jacobtomlinson.github.io\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [".travis.yml",
          ".gitignore",
          "Gemfile*",
          "README.md",
          "LICENSE",
          "Rakefile",
          "CNAME"]
