baseURL = "https://www.jacobtomlinson.co.uk/"
languageCode = "en-gb"
title = "Jacob Tomlinson"
theme = "carte-noire"
pygmentsCodeFences = true
disqusShortname = "jacobtomlinson"

[permalinks]
    posts = "/:section/:year/:title/"

[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss"
baseName = "feed"
