name: "Nightly build"
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build
        run: curl -X POST -d {} ${{ secrets.NETLIFY_NIGHTLY_WEBHOOK }}
